#!/bin/sh -e

SA_SUFFIX=$(echo "$DOMAIN_NAME" |tr '[:upper:]' '[:lower:]'|cut -d "." -f1)
# Service account name must be between 6 and 30 characters (inclusive), 
# must begin with a lowercase letter, and consist of lowercase alphanumeric 
# characters that can be separated by hyphens.
SA_NAME="$(echo "$HUB_COMPONENT"-"$SA_SUFFIX" | cut -c1-29| tr '[:upper:]' '[:lower:]'| tr '_' '-')x"
SA_EMAIL="$SA_NAME@$PROJECT.iam.gserviceaccount.com"

if gcloud iam service-accounts describe "$SA_EMAIL" > /dev/null; then
  echo "Service account: $SA_EMAIL (already exists)"
else
  gcloud iam service-accounts create "$SA_NAME" --project="$PROJECT" --display-name="$SA_NAME"
fi

gcloud projects add-iam-policy-binding "$PROJECT" \
    --member "serviceAccount:$SA_EMAIL" \
    --role roles/dns.admin  

gcloud iam service-accounts add-iam-policy-binding "$SA_EMAIL" \
  --role roles/iam.workloadIdentityUser \
  --member "serviceAccount:$PROJECT.svc.id.goog[$NAMESPACE/$HUB_COMPONENT]"
