#!/bin/bash -e

USER_ACCOUNT="$(gcloud --format=json auth list | jq -cMr --arg u "$USER" '.[] | [select(.status == "ACTIVE"), {account: $u}] | first | .account')"
dotenv set "USER_ACCOUNT" "$USER_ACCOUNT"
